### PR TITLE
Implement drawable for expand/collapse

### LINKED ISSUE #276: Triangle for Evolution displays as emoji
Alt Text

Will try out another set of Unicode symbols that wouldn't get converted to emoji in certain devices.

### PR DESCRIPTION
**Pull request by DJCrapsody**
Looks prettier than having a unicode in a textview.

EDIT: fixes #276.

### CODE REVIEW

**Comment by DJCrapsody** [comment]
fixes https://github.com/farkam135/GoIV/issues/276

**Comment by Blaisorblade** [comment]
Thanks! I'd like a review by @oskomonzon here.

**Comment by oskomonzon** [comment]
@Blaisorblade I apporve of this change. Let's have @nahojjjen giving it a look.

The alingment seems a little off on my device, I'm not sure if that's intended (and a matter of personal taste) or it's just something that happens on my screen density (Not home at the moment, I can't test it on more devices).

:+1:

**Comment by Blaisorblade** [comment]
@oskomonzon IIUC, that's because there's embedded padding in all the `png`s? I guess all the padding should be done in the XML instead (and below there should be none).

**Comment by DJCrapsody** [comment]
I trimmed all paddings on Android Asset Studio. Will check on the arrows again. I took the 18dp reference from the previous text based icon, maybe I will try 24dp instead.

**Comment by Blaisorblade** [comment]
Re paddings, I just looked at the PNGs in GitHub so it might well be nonsense.

**Pull request merged**
