### PR TITLE
Attempt to fix appraisal refining crash on 4.4 devices

### LINKED ISSUE #475: Appraisal Refining in screenshot mode crash on Android 4.4
Clicking "Appraisal Refining" instantly crashes GoIV 3.2 showing the "Unfortunately GoIV has stopped." dialog.
This happens on my tablet (cm11/android 4.4) but not on my phone (android 6).

### PR DESCRIPTION
**Pull request by DJCrapsody**
Attempt to fix #475

NOTE: THIS IS YET TO BE TESTED! DO NOT MERGE!

@thearaks require your testing on your 4.4 device

Tested on 6.0.1, and don't see any changes (except for the font change), or having any crashes. This is just to test if it crashes on 4.4, any unintended minor UI changes only to be fixed after the crash is fixed on 4.4.

### CODE REVIEW

**Comment by thearaks** [comment]
The arrow beside refine appears but, as soon as I click it:

`10-05 20:17:02.049 8257-8257/com.kamron.pogoiv E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.kamron.pogoiv, PID: 8257
                                                                 android.view.InflateException: Binary XML file line #2: Error inflating class android.widget.CheckedTextView
                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
                                                                     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                     at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:371)
                                                                     at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
                                                                     at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
                                                                     at android.widget.Spinner.onMeasure(Spinner.java:482)
                                                                     at android.view.View.measure(View.java:16497)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                     at android.view.View.measure(View.java:16497)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                     at android.view.View.measure(View.java:16497)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                     at android.view.View.measure(View.java:16497)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                     at android.view.View.measure(View.java:16497)
                                                                     at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
                                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                     at android.widget.ScrollView.onMeasure(ScrollView.java:326)
                                                                     at android.view.View.measure(View.java:16497)
                                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                     at android.view.View.measure(View.java:16497)
                                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
                                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: java.lang.reflect.InvocationTargetExc
`

**Comment by DJCrapsody** [comment]
@thearaks can you try this again? I'm just doing random changes hoping something would work.

**Comment by thearaks** [comment]
@DJCrapsody Everything is working now!

**Comment by Blaisorblade** [comment]
Whoops I missed this. Merging!

**Comment by DJCrapsody** [comment]
Ahh wanted to change some stuff. It's ok, will do it while fixing the color issues! :)

**Comment by Blaisorblade** [comment]
Hey, we have a weirder font now?

**Pull request merged**
