### PR TITLE
Update DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by DJCrapsody**
Fix capitalization for consistency
Add instruction on setting project's code style scheme
This will prevent accidental commits on code style settings

### CODE REVIEW

**Comment by Blaisorblade** [comment]
LGTM! Anybody else try this?

**Comment by nahojjjen** [comment]
I performed  

>  Copy the Project's Code Style Scheme (File > Settings > Editor > Code Style > Scheme > Manage > Select 'Default' > Copy to Project)

but android studio still seems to reset codestylesettings for me

**Comment by DJCrapsody** [comment]
It also happened to me when I was trying out the options. I had it working only on a fresh clone.

**Comment by Blaisorblade** [comment]
Since the instructions (as given) are correct, merge this. I guess I'd mention this caveat.

I suspect the difference in behavior depends on the other files in `.idea`—most of them are not under version control.

**Pull request merged**
