### PR TITLE
Modified the autoupdater

### LINKED ISSUE #222: Updater won't run in background
Is the updater working correctly? It won't continue downloading unless I keep the application on the foreground, switching it to the background will make the download stop, trying to continue it will just get a new copy downloaded, ended up with 8 or so update.apk files, several corrupted. And didn't run the apk installer after it finished downloading.

### PR DESCRIPTION
**Pull request by rhari991**
Is a work in progress
1) Removed the EventBus library as it was not being used anywhere else in the project. Replaced it with a BroadcastReceiver.
2) The download should be carried out in a service now.

The apk file is not being started after the download has been completed. Going to bed, will finish this up once I am awake.

EDIT: Fix #222.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
I'd like a chance to review this, but right now the diff shows existing changes mixed with new ones...

**Comment by rhari991** [comment]
That happened when I rebased it - Is there a way to avoid it ? Sorry, I'm not too good with Git.

**Comment by Blaisorblade** [comment]
That can happen if you merge and then rebase... In the future, I guess better avoid rebase unless you're a Git expert. Just go ahead, if I care I'll view the diff locally.

**Comment by Blaisorblade** [comment]
> That can happen if you merge and then rebase... In the future, I guess better avoid rebase unless you're a Git expert. Just go ahead, if I care I'll view the diff locally.

Turns out that this is just GitHub being stupid. Sorry go ahead.

**Comment by rhari991** [comment]
Should be good to go. Can you test it please ?

**Comment by Blaisorblade** [comment]
1. Can we close this PR and open a new one with the same branch? So that Git shows something I can review.
2. How do I test this? I guess I have to make a build marker as 3.0.0 or sth. and try upgrading it to 3.0.1? Or is there sth. simpler?

**Comment by Blaisorblade** [comment]
> How do I test this? I guess I have to make a build marker as 3.0.0 or sth. and try upgrading it to 3.0.1? Or is there sth. simpler?

That's not needed, because `master` is marked internally as 3.0.0 already :-(.

I triggered an update and went to the home screen, and this worked (modulo unavoidable signature mismatch). That's great!

Then I tried triggering an update and exiting the activity—the download continued correctly, but I got a couple of stack traces (that I'll add in next post).

There's also a couple of issues that might have less to do with this PR:
- pressing "check update" shows the changelog dialog for 3.0.1, then pressing cancel and going back shows the changelog dialog again;
- pressing "check update", accepting the update, and exiting settings and the app shows the changelog dialog *two times*;
- no version check is shown when booting, even when "Auto-update" is enabled.

**Comment by Blaisorblade** [comment]
Here's the logs from logcat—grepping for `goiv`:

```
08-28 17:07:27.197 797-2038/? I/ActivityManager: Killing 7072:com.kamron.pogoiv/u0a211 (adj 16): remove task
08-28 17:07:27.295 797-1043/? W/ActivityManager: Scheduling restart of crashed service com.kamron.pogoiv/.updater.DownloadUpdateService in 1000ms
08-28 17:07:28.310 797-810/? I/ActivityManager: Start proc 11435:com.kamron.pogoiv/u0a211 for service com.kamron.pogoiv/.updater.DownloadUpdateService
08-28 17:07:30.091 11435-11435/com.kamron.pogoiv D/AndroidRuntime: Shutting down VM
08-28 17:07:30.093 11435-11435/com.kamron.pogoiv E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.kamron.pogoiv, PID: 11435
                                                                   java.lang.RuntimeException: Unable to start service com.kamron.pogoiv.updater.DownloadUpdateService@e860b02 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
                                                                       at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
                                                                       at com.kamron.pogoiv.updater.DownloadUpdateService.onStartCommand(DownloadUpdateService.java:21)
                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
                                                                       at android.app.ActivityThread.-wrap17(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
08-28 17:07:31.024 11435-11491/com.kamron.pogoiv E/Fabric: Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.kamron.pogoiv/settings
08-28 17:07:31.028 11435-11493/com.kamron.pogoiv E/Answers: Failed to retrieve settings
08-28 17:07:31.783 11435-11435/com.kamron.pogoiv I/Process: Sending signal. PID: 11435 SIG: 9
08-28 17:07:31.822 797-2040/? I/ActivityManager: Process com.kamron.pogoiv (pid 11435) has died
08-28 17:07:31.822 797-2040/? W/ActivityManager: Scheduling restart of crashed service com.kamron.pogoiv/.updater.DownloadUpdateService in 1000ms
08-28 17:07:32.837 797-810/? I/ActivityManager: Start proc 11577:com.kamron.pogoiv/u0a211 for service com.kamron.pogoiv/.updater.DownloadUpdateService
08-28 17:07:33.716 11577-11577/com.kamron.pogoiv D/AndroidRuntime: Shutting down VM
08-28 17:07:33.717 11577-11577/com.kamron.pogoiv E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.kamron.pogoiv, PID: 11577
                                                                   java.lang.RuntimeException: Unable to start service com.kamron.pogoiv.updater.DownloadUpdateService@e860b02 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3027)
                                                                       at android.app.ActivityThread.-wrap17(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
                                                                       at com.kamron.pogoiv.updater.DownloadUpdateService.onStartCommand(DownloadUpdateService.java:21)
                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
                                                                       at android.app.ActivityThread.-wrap17(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
08-28 17:07:34.577 11577-11640/com.kamron.pogoiv E/Fabric: Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.kamron.pogoiv/settings
08-28 17:07:34.580 11577-11640/com.kamron.pogoiv E/Answers: Failed to retrieve settings
08-28 17:07:36.933 11577-11577/com.kamron.pogoiv I/Process: Sending signal. PID: 11577 SIG: 9
08-28 17:07:37.043 797-9737/? I/ActivityManager: Process com.kamron.pogoiv (pid 11577) has died
08-28 17:07:37.052 797-9737/? W/ActivityManager: Service crashed 2 times, stopping: ServiceRecord{f0086 u0 com.kamron.pogoiv/.updater.DownloadUpdateService}
08-28 17:08:28.217 31526-12110/? W/DownloadManager: Missing request for path /storage/emulated/0/Android/data/com.kamron.pogoiv/files/Download/GoIV_new.apk
```

**Comment by rhari991** [comment]
I'm shifting to a new PC, so I might take a bit of time. Once I'm done, I'll make a new PR and fix the above issues.

**Comment by Blaisorblade** [comment]
Sure, no big hurry.
Regarding the double dialog: there are multiple calls to `getAppUpdateDialog` in response to the intent notifying an update, I guess only one should be active at any time.

**Comment by Blaisorblade** [comment]
Closing meanwhile as discussed.

**Pull request closed without merging**
