### PR TITLE
Prepare for releasing 3.2

### PR DESCRIPTION
**Pull request by Blaisorblade**
The changelog is based on @nahojjjen's, but he said we might want to take another look.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
If this is OK I recommend a squash merge—the separate commits only highlight the changes to the original.

**Comment by sarav** [comment]
Squash merge seems like the right thing to do for a change log.

**Comment by Blaisorblade** [comment]
Whoops, I screwed that up :facepalm:

**Comment by sarav** [comment]
How? By not squashing? Everything else seems fine.

**Pull request merged**
