### PR TITLE
Shorten/make the appraisals more consistent

### PR DESCRIPTION
**Pull request by imapokemon4**
I noticed that some of the appraisal phrases were shortened and others were word for word.
  
This PR makes them all <s>word for word</s> shortened. EDIT: updated by @Blaisorblade.

### CODE REVIEW

**Comment by nahojjjen** [comment]
The reason was because when I created the appraisal input I made two spinners to pick the phrases which were on the same row, and they needed to fit the screen width. And Im on mystic, and I only tested for mystic & told other people to shorten their team phrases.

Ill test and see how these longer phrases work now

**Comment by Eccenux** [comment]
Don't think it's a good idea. If you have full sentences then you have to read everything instead of just focusing on a few words. And besides even on full wide they barely fit on the screen.

**Comment by Blaisorblade** [comment]
I'd like more consistency if possible, and trying to shorten them if possible sounds more functional. Using ellipsis to highlight what's shortened is also good.

**Comment by imapokemon4** [comment]
I've committed my best effort at shortening everything while keeping everything as consistent as possible.

**Comment by Blaisorblade** [comment]
Thanks! What do people think?

Before merging, you might want to merge or rebase with master.
I'd prefer to keep a literal ellipsis rather than `&#`, since the former is more readable, as long as it works.

**Comment by imapokemon4** [comment]
@Blaisorblade Rebased with your instructions.

**Comment by Blaisorblade** [comment]
Thanks, but there's still a conflict, it's not rebased on the latest master. Anyway, I think this is a good basis for getting started! What do the others think?

**Comment by imapokemon4** [comment]
@Blaisorblade 
  
Did I do it correctly? Do I have to rebase again after that merge?

**Comment by imapokemon4** [comment]
@Blaisorblade 
  
I tried some more rebasing and squashing. I'll leave it alone now until you tell me what I need to do next.

**Comment by Blaisorblade** [comment]
I'm now inclined to merge this: long phrases are especially a problem when the spinners are closed (after picking, in case you're rechecking), beyond being too long to read.

I'll wait a bit for opinions.

**Comment by nahojjjen** [comment]
My opinion is that it looks good.

**Pull request merged**
