### PR TITLE
Refactoring to make pokefly more readable 

### PR DESCRIPTION
**Pull request by nahojjjen**
This commit takes the pokemon IV analysis logic from pokefly and moves it to a class "PokeInfoCalculator". 

So for example, pokefly no longer creates its IV text in a huuuge blob. It instead asks for an IVScanResult for a pokemon, and then populates the string with information from the scan result.

### CODE REVIEW

**Comment by hlplulustg** [comment]
It's showing the wrong pokemon name for the scanned one (Mew). Calculations still correct.

**Comment by hlplulustg** [comment]
[https://cdn.discordapp.com/attachments/215438329024348161/215884739129769984/Screenshot_20160818-192816.png](https://cdn.discordapp.com/attachments/215438329024348161/215884739129769984/Screenshot_20160818-192816.png)

**Comment by hlplulustg** [comment]
Was a user error (renamed pokemon), seems to be fine.

**Comment by nahojjjen** [comment]
I killed this branch to make a new one without conflicts, see #75

**Pull request closed without merging**
