### PR TITLE
Load credentials from keystore.properties

### PR DESCRIPTION
**Pull request by imapokemon4**
I don't know how everyone else generates signed release builds, but I thought this might be helpful.

Please let me know if there is a better way.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Restarted the build, the last failure was spurious (network problems in installing dependencies).

**Comment by Blaisorblade** [comment]
Thanks for the PR!

It'd be good to add a `keystore.properties.sample` to show the format. And generally to have a description of what you're doing and your goals.

Personally, I looked into something like this so we could build a fake release version on travis (not your goal), and maybe to build one myself. If we store the key securely (which might be possible), Travis might be able to build actual releases (maybe we want a separate key though).

Finally, I don't know how @farkam135 does his release builds, and it'd be bad to break his workflow (but probably he just needs to fill in the config the right way).

We might also also need to link to a guide to generate the keystore—the tutorial in the Android docs (https://developer.android.com/studio/publish/app-signing.html) is decent, using the tools by hand IIRC is painful. (Not because it's CLI, but because `keytool` and its docs are awful).

**Comment by imapokemon4** [comment]
`git push --force` to the rescue!

**Comment by DJCrapsody** [comment]
LGTM

**Comment by imapokemon4** [comment]
imapokemon4
  
I'm a contributor! :)

**Pull request merged**
