### PR TITLE
Resources over Hard coding data

### PR DESCRIPTION
**Pull request by McAJBen**
I moved the hard coded pokemon base stats to be in a resource file.

### CODE REVIEW

**Comment by nahojjjen** [comment]
I like the idea and i think the pull should be accepted, but it does slightly inconvenience #24 since that issue requires an extra field to be added

**Comment by nahojjjen** [comment]
Okay why did you close this so suddently

**Comment by McAJBen** [comment]
When I transfered to resource file I might have missed something, the values might be off by one

**Comment by nahojjjen** [comment]
I see

**Comment by McAJBen** [comment]
I'll re-open after I make sure it's fixed

**Pull request closed without merging**
