### PR TITLE
Fix IV button size and location

### LINKED ISSUE #402: IV button is not sized correctly
iv-wrong-size

Reported at https://www.reddit.com/r/GoIV/comments/50s7uf/version_310_released/d7hiykj

### PR DESCRIPTION
**Pull request by DJCrapsody**
Incompleted, sizes were based on DPI resizing, PoGo menu button is not
Location of the button is adjusted to the nearest possible location (not exact)
Tested on: xxxhdpi
Require screenshot of pokemon screen of mdpi, hdpi and xhdpi devices

DO NOT MERGE.

Fix #402

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Thanks for working on this! Maybe you know, but it seems like this version also changes the button, specifically the orientation of the gradient inside the IV letters—is that expected?

**Comment by DJCrapsody** [comment]
If you actually look closely, fhe word IV for the original version and my version are done the same way, using the 3 lines from the menu button. I haven't found a font that fits it so this will be the interim.

**Comment by Blaisorblade** [comment]
> If you actually look closely, fhe word IV for the original version and my version are done the same way, using the 3 lines from the menu button.

Ah, clever! The darker green was up and now is down—apparently you rotated the three lines the other way around. But probably the direction is just random, so whatever.

**Comment by DJCrapsody** [comment]
Maybe I rotated wrongly haha. But using the 3 lines were a little dirty anyway.

**Comment by DJCrapsody** [comment]
http://www.dafont.com/odin-rounded.font?text=IV

Looks good?

**Comment by DJCrapsody** [comment]
@Blaisorblade here's the proper gradient following the menu button!

**Comment by Blaisorblade** [comment]
Love that part! Let me know when you've addressed the other issues you mention.

**Comment by sarav** [comment]
@DJCrapsody I can test this out in my tablet where the current button is tiny. But it's going to be only on the weekend. That'll show how well these changes work.

Btw, why not just use Roboto for fonts? Also, I think we should stop picking the color from the game (do we detect this at run time?). They way, we might be able to get this back on the play store with the description being:

Calculate IV for all the fullscreen screenshots that you can open in any image viewer? And then the app will just coincidentally also work on anything that shows the Pokemon screen in full screen view.

**Comment by DJCrapsody** [comment]
@sarav I require the opposite, when the screen is small. But will be great if you can test it on your tablet. Hopefully the size turns out well.

RE: font and colors, maybe we can open a separate issue on this? Doesn't seem to link to the PR.

**Comment by sarav** [comment]
I thought you were going to make it a real character and font in this PR. If not, yeah, we can make separate issue...
...
...
...
and you can work on it :P

**Comment by DJCrapsody** [comment]
We can make odin as our main font.... and everything's going to be rounded 😛 
224 ppi pixel should be hdpi. Seems like we can test that!

**Comment by DJCrapsody** [comment]
Finally got to rebase this properly.
@sarav are you able to provide the tablet screenshot soon?

**Comment by sarav** [comment]
@DJCrapsody Sure.

**Comment by sarav** [comment]
Here they are. Seems to make no difference AND the current placement is not even close to right (doesn't bother me much though).

Without your changes:
screenshot_20160917-153025

With your changes:
screenshot_20160917-155757

**Comment by DJCrapsody** [comment]
PR closed as this will be merged with reducing apk size with drawables. New PR will be created.
Unfortunately, this button will not be able to be converted to SVG.

**Pull request closed without merging**
