### PR TITLE
Color IV based on appraisal thresholds

### PR DESCRIPTION
**Pull request by leppie**
Use text color based on Appraisal system.

image

### CODE REVIEW

**Comment by Blaisorblade** [comment]
> Use text color based on Appraisal system.

That could be fine with me, I'd let the others decide.

> Show IV percent to 1 decimal point in possibilities.

We're talking about the individual possibilities right? That was discussed at length and rejected.

Also decimals add no information: A single IV percentage can be 84%, 87% or 89%, nothing in the middle that needs decimals; a single IV point gives a difference of 2.222%. There's no point showing those are really 84.444...% or 86.666...% or 88.888...%.

**Comment by leppie** [comment]
Ok, I'll bin the decimal point. Should I remove the % sign too?

**Comment by Blaisorblade** [comment]
> Should I remove the % sign too?
I guess yes. That'd leave only "Use text color based on Appraisal system".

For the rest, does @nahojjjen or @oskomonzon have a preference?
And if possible, please have one commit with descriptive title, like "Use text color based on Appraisal system".

**Comment by leppie** [comment]
All done. Another idea might be to multi level check boxes for appraisal hints too.

Eg: 1 click makes check, subsequent cycles the matching colors, then clear again.

**Comment by DJCrapsody** [comment]
Would be good if the javadoc comments are updated to match the current codes.

**Comment by leppie** [comment]
Will do

**Comment by Blaisorblade** [comment]
We're nearing a release so I'd like to minimize changes and potential regression—it's not like we have an extensive test suite.

> Another idea might be to multi level check boxes for appraisal hints too.
> 
> Eg: 1 click makes check, subsequent cycles the matching colors, then clear again.

For now probably not—but feel free to open an issue with a clearer description.

> All done.
>
> Edit: Arghhhh, number formatter did something stupid...

I'd guess just take away that entire part of the change—no reason to change `percentPerfect` to `double`.

**Comment by leppie** [comment]
> I'd guess just take away that entire part of the change—no reason to change percentPerfect to double.

Leaving it as is, from the diff it looks cleaner :) And who knows, maybe it will be needed later if the game devs change stuff again.

**Comment by Blaisorblade** [comment]
> Leaving it as is, from the diff it looks cleaner :)

I'm looking for a minimal diff, and I'm rejecting changes to the core logic next to a release.

> And who knows, maybe it will be needed later if the game devs change stuff again.

That's a bad argument. I find those changes a regression.

**Comment by leppie** [comment]
OK, reverted back to int, also adjusted to midpoints to work correctly with ints.

**Comment by Blaisorblade** [comment]
If possible, I'd like @oskomonzon's opinion on the design (basically on the color choice), since he's our master designer. But otherwise LGTM.

**Comment by leppie** [comment]
The blueish was picked at random :)

**Comment by nahojjjen** [comment]
I'd like to avoid blue coloring, as it does not fall into the intuitive red-orange-yellow-green spectrum that people are used to for seeing how perfect something is.

**Comment by Blaisorblade** [comment]
Maybe blue -> orange would be an improvement?

**Comment by nahojjjen** [comment]
I'd like clarification of what the change actually is in this PR. The ivs are already color coded, so what this pr does is change the color coding - why, and to what?

**Comment by oskomonzon** [comment]
I agree with @nahojjjen on this one. I'm not against the overall idea but we need to avoid introducing changes that lead to user confusion, I feel the blue would fall in that category.
To clarify: I don't mind at all the change to 4 steps of distinction, but I'd say we stay in the green to red spectrum.

**Comment by oskomonzon** [comment]
@nahojjjen as far as I understand what's propossed here... I think the objective is to match the color coding to the different phrases the team leader uses to distinct IV ranges.

Instinct, as an example, goes by: 
80% - 100% : Overall, your (Pokemon Name) looks like it can really battle with the best of them!
67% - 79% : Overall, your (Pokemon Name) is really strong!
51% - 66% : Overall, your (Pokemon Name) is pretty decent!
0% - 50% : Overall, your (Pokemon Name) has room for improvement as far as battling goes.

So he wants the color code in four steps to match that.

**Comment by Blaisorblade** [comment]
See the table on [GamePress](http://pokemongo.gamepress.gg/pokemon-appraisal) for the correct ranges (there are slight differences)—the PR itself is fine there.

**Comment by Blaisorblade** [comment]
@oskomonzon Are you fine with any orange or do you want to pick colors that match with some care?

**Comment by leppie** [comment]
Would the color ordering be the like this? 

image

**Comment by oskomonzon** [comment]
Thanks, @Blaisorblade, I updated my comment.
Maybe we can borrow colors from the Material Design color palette (https://material.google.com/style/color.html#color-color-palette, all praise Duarte).

I'm not on the computer right now, but I guess something like this can work:
#F44336 - Red
#FF9800 - Orange
#FFEB3B - Yellow
#4CAF50 - Green

**Comment by oskomonzon** [comment]
@leppie I'd avoid too vibrant/washed colors to prevent hurting readability.

**Comment by leppie** [comment]
@oskomonzon Yes, of course, was just interested in the ordering.

**Comment by oskomonzon** [comment]
@leppie, ordering makes sense :+1: 
What do you think about those?, same for @nahojjjen. Keep in mind I'm just guessing, I will not be able to see them in action uptil later.

**Comment by leppie** [comment]
I will make a build and post a screenshot

**Comment by leppie** [comment]
The yellow is quite washed out... :(

I will wait for better suggestions :)

image

**Comment by nahojjjen** [comment]
I find it confusing that the % and the ivs do not use the same color scale.

**Comment by leppie** [comment]
A bit off-topic, but can one add sorting on that listview, so clicking on any column/column header will toggle it?

**Comment by leppie** [comment]
@nahojjjen: Maybe that can be an option, so user has choice.

**Comment by Blaisorblade** [comment]
Re confusion: that's true, but the scales come externally. The colors could help compare the results 
with appraisals. OTOH, we might just add extra appraisal checkboxes.

> A bit off-topic, but can one add sorting on that listview, so clicking on any column/column header will toggle it?

That is probably a good idea. We've wanted to sort by attack first and somehow nobody did a PR. What you're proposing is probably possible but will certainly have to wait a while longer (we need to close 3.1 and refactor things).

**Comment by oskomonzon** [comment]
I share @nahojjjen's concern about the different scaling in the color codes.
To be a little more clear, we are creating a scenario where the color value means something different depending on the data we are displaying...
For stats (Atk, def, sta) Green means 15 (The maximum value for that stat, 100%, so to speak)
On the other hand, for IV% Greens would mean "above 82%".

**Comment by Blaisorblade** [comment]
Also: yes it's conceivable, so please file an issue so we don't forget about it. Same for your other idea (that I didn't even get).

And to be sure: thanks for your proposals!

> Maybe that can be an option, so user has choice.

We're trying to avoid having options for everything—it's more confusion for the user and more testing (currently manual) to get it right.

**Comment by Blaisorblade** [comment]
Since we're not sure yet, scheduled for after the refactorings.

**Comment by Remiscan** [comment]
I think red-orange-yellow-green is a bit confusing, because yellow makes these results look bad/average when they're actually good (13 or 14 isn't bad at all), and orange makes them look bad when they're average to quite good. Maybe something like red-yellow-lighter green-green?

**Comment by oskomonzon** [comment]
@Remiscan that makes sense. I'd use orange instead of yellow in that case.

**Comment by oskomonzon** [comment]
Overall, I like the idea, but I'm conflicted by the lack of consistency as explained earlier (https://github.com/farkam135/GoIV/pull/336#issuecomment-244146439).

**Comment by leppie** [comment]
Went back to original colors, and changed the blue I added to a khaki green, which does look kinda nice.

image

**Comment by Remiscan** [comment]
I think it looks better, but thak khaki green doesn't make me feel as if the result is "good" enough. I think I'd go with something a bit "greener", like #99CC00 although that may be too vivid.

I also find the lack of consistency a bit confusing, and I felt like making the colors closer to one another by having two shades of green would make the difference less "shocking". But seeing the last screenshot, it still looks a bit confusing.

**Comment by DJCrapsody** [comment]
IMO, too much colors. My suggestion would be the entire row will use the same color based on % IV. Then bold the highest IV(s) for the row. IV don't make a very significant difference compared to movesets.

**Comment by amcameron** [comment]
I disagree, @DJCrapsody. If IVs are unimportant then uninstall GoIV and just use the built-in appraisal system. Movesets are more important than IVs, but how do you distinguish between Pokémon at different levels with the same movesets?

Bolding the highest entries in each row would be redundant because of the optional Appraisal input step before you activate the "Check IVs" button.

Personally, I like the colours best in the very first comment on this pull request, although I would switch blue and green. Bad/red, decent/yellow, good/green, excellent/blue. This way, the "strong" range still looks good, and the absolute best are special.

The lack of consistency mentioned by @oskomonzon does not bother me. To me, there is no lack of consistency: one is used based on the percentage range of the IV sum, and the other is for discrete IVs between 0–15, and in both cases the colour thresholds change with the appraisal feedback thresholds. To me, colour-coding only based on value is pointless visual flair. The colours are useful if they allow me to look up entries based on the appraisal feedback; otherwise, they simply distract and there's no point having a three- or four-element colourmap and you might as well use 46 distinct colours, one for each possible IV%.

**Comment by Blaisorblade** [comment]
> The colours are useful if they allow me to look up entries based on the appraisal feedback

That again. I also refine results by hand and think we should go the full way (everybody kind of agrees). So the highlighting should IMHO be designed assuming we do that.

https://github.com/farkam135/GoIV/issues/341#issuecomment-244556217

**Comment by amcameron** [comment]
Another idea, instead of using four colours or a different shade of green, is to use the same shade of green for IVs from 13–15, and for 15 to also draw a shadow with TextView.setShadowLayer(). That would avoid subjective opinions about colour while emphasising the different appraisal tiers.

**Comment by Remiscan** [comment]
I tried a few colour combinations so I thought I'd show everyone: 
- Light Green / Dark Green : http://i.imgur.com/b1rgsOE.png (I like this one)
- Green / Dark Green : http://i.imgur.com/2MrQO4k.png
- Green / Turquoise : http://i.imgur.com/XSG56kJ.png (and that one too)
- Green / Blue : http://i.imgur.com/HUvqkHl.png
- Dark Green / Blue : http://i.imgur.com/qT99AJZ.png

I think shadows may look weird but I will try and see.

**Comment by leppie** [comment]
Maybe the colors for IV and % should be different (one darker than other?), but follow the same 'progression' .

**Comment by amcameron** [comment]
IMHO of those ones I like Green/Blue or Dark Green/Blue the best.

**Comment by leppie** [comment]
I like these ones the most:
* Light Green / Dark Green 
* Dark Green / Blue

**Comment by crd** [comment]
As a neutral third party I agree:

* coloring should be consistent with appraisal values
* I'm not too worried about misleading colors -- users of GoIV are sharp enough to understand what's happening
* I would optimize for visibility, not red -> green coloring. It's obvious that a 15 is better than a 7
* inconsistent coloring across appraisals versus overall percentage doesn't bother me. Take that one up with nuantic

Looking forward to this PR (or a variant) being accepted!

**Comment by Blaisorblade** [comment]
In the end I've merged this PR with the existing colors, mostly to make progress and because the resulting code is also a bit cleaner.

In the end consistency among different things isn't to be expected. Maybe it'd be better to use disjoint sets of colors for the two scales to reduce ambiguity, but that requires enough colors that are different enough.

I've opened #388 to remember to track the color choice—I'll leave that to somebody else.

**Pull request merged**
