### PR TITLE
Save corrections on spinner item selection

### PR DESCRIPTION
**Pull request by Blaisorblade**
Address @sarav's TODO mentioned in #295. Tested, but might be a bad idea. *Don't merge yet.*
It also conflicts with other ongoing PR #308 IIUC.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Actually: should the correction be saved as correct if the user doesn't change it but clicks OK? Or when he clicks OK and valid combinations are found?

**Comment by Blaisorblade** [comment]
This PR is about explicit user corrections should be just explicit user corrections. I'm not sure we should save those if you correct and then click cancel, though—something that doesn't happen now and happens after this PR. So I doubt this is a good idea.

**Comment by Blaisorblade** [comment]
While we debate this, closing for now. We can continue discussion here.

**Comment by sarav** [comment]
I think you should squash the 2 commits. Final history don't need to see mistakes we made while coding.

I see your point about this saving user corrections before they click any button. But I don't think it's very likely that the user will change the spinner but not click "Check IV". So, I don't think it's a big deal. However, we can still address your concern -- set a flag when user selects something on the spinner. And we'll save it only if the flag is set AND we meet the existing conditions in that "if".

**Pull request closed without merging**
