### PR TITLE
Fix recognition of portuguese candy names

### PR DESCRIPTION
**Pull request by onilton**
Portuguese has "doces" (candy) coming first in candy name.

### CODE REVIEW

**Comment by nahojjjen** [comment]
Just to prove this change is correct, could you show / link a screenshot where the candy comes first? It looks like a good PR, I just want to make sure. :)

**Comment by onilton** [comment]
Screenshot

**Comment by onilton** [comment]
I think in the future we will have to split portuguese BR and portuguese (Portugal)

**Comment by onilton** [comment]
Since portugal portuguese doesn't seem to have translation but portuguese BR does.

**Pull request merged**
