### PR TITLE
Major clean up on gradle and libraries

### PR DESCRIPTION
**Pull request by DJCrapsody**
Clean up gradle script and insert comments
Remove unnecessary tess-two library files (compile from repo)
Fix proguard error with okio (compile okio library instead of ignoring)
Update various libraries

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Travis failure genuine—you need to update major dependencies like build-tools in `.travis.yml` as well.

**Comment by DJCrapsody** [comment]
Yeah that's what I wanted to put as comment. Haha. Gotta update Travis brb.

**Comment by Blaisorblade** [comment]
I've taken the deletions into master, can you force-push or rebase so that GitHub notices now the diff is something that can be shown?

**Comment by Blaisorblade** [comment]
I squashed and merged it.

**Comment by imapokemon4** [comment]
In order to get a release build to work I had to put dontwarn back into the proguard-rules.

**Comment by Blaisorblade** [comment]
@imapokemon4 Thanks! Just confirmed for the offline release build. It's a pity our Travis build doesn't test it.
@DJCrapsody I reverted that part.

**Pull request closed without merging**
