### PR TITLE
Updated README to 2.2.0

### PR DESCRIPTION
**Pull request by DJCrapsody**

### CODE REVIEW

**Comment by jehy** [comment]
Change log should show corresponding version.

**Comment by DJCrapsody** [comment]
Possibly redundant as version is stated under Download. If there is one more objection with my reasoning, I will put the version back in the header.

**Comment by jehy** [comment]
Change log should be kept for all versions, not only for last one.

**Comment by Blaisorblade** [comment]
I agree the changelog should include older changes, but maybe not inside the README? We could have a ChangeLog.md file in the repo and link to it, and put there the latest release on top.

**Comment by jehy** [comment]
Yup, separate change log is fine too.

**Comment by Blaisorblade** [comment]
I think we can merge this too since the README is still out of date; I'll accept PRs to improve this further as discussed.

**Pull request merged**
