### PR TITLE
Improve efficiency of evolution tracking and Google now support

### PR DESCRIPTION
**Pull request by sarav**
Fixed up my earlier pull requests and pushing them again.

I also addressed comments made on the earlier pull request for the evolution tracking. The code no longer assumes any relation between pokemon and their devolutions.

### CODE REVIEW

**Comment by sarav** [comment]
Both changes have been tested and seem to work fine.

**Comment by sarav** [comment]
@nahojjjen In regards to your earlier comment that the app should say something if an image is shared but the GoIV service isn't running, I'd like to show a Toast show some message along those lines. But I'm not sure what's the proper way to get the actual text from the XML files and put in translations. Do you want to do that change? It could say something like "The GoIV service needs to be started first".

I also want to warn users of not trying to share an old screenshot and get bad IV numbers, but I don't know how to enforce or warn for that.

**Comment by nahojjjen** [comment]
I'm one of those dirty programmers that consistently hard-code strings, so I dont have much knowledge in this field

**Comment by sarav** [comment]
Also, "Minor text fixes" :smiley:

**Comment by sarav** [comment]
@farkam135 I might not be using pull requests correctly, but looks like you missed [this commit](https://github.com/farkam135/GoIV/pull/109/commits/5a7204e296e79064513252e6e31361e1c2e7046d) because I updated the pull request.

**Comment by sarav** [comment]
Nevermind, looks like you did. I'm just confused by github interface.

**Pull request merged**
