### PR TITLE
Minor text fixes

### PR DESCRIPTION
**Pull request by imapokemon4**
I removed the same unused variables for the other localizations and rebased.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Can you name the commit (and the PR) something like "Removed unused strings"? I get the running joke, but looking at git logs is not meant to be fun 😉

**Comment by imapokemon4** [comment]
Not a joke. It's that same commit you just merged.

**Comment by imapokemon4** [comment]
@Blaisorblade is that correct?

**Comment by DJCrapsody** [comment]
Minor text fixes  

http://knowyourmeme.com/memes/pokemon-go-updates-controversy

**Comment by Blaisorblade** [comment]
Thanks to @DJCrapsody for finding the meme!

> It's that same commit you just merged.

It's not "the same". But it seems a revised version. Please don't. The original commit was merged (which was... probably bad), now we can only merge a new one. Two commits with the same title is typically bad (GitHub even shows again the same changes 😢  which doesn't help).

And neither should be called "Minor text fixes", but should have an informative title. If you disagree, please take a look to https://github.com/farkam135/GoIV/blob/master/DEVELOPMENT.md#writing-good-commit-messages and/or to the linked article.

**Comment by Blaisorblade** [comment]
Apologies if my comments sounded overly negative, that was not my intention but might have been unclear. Since the OP argued about why you used git this way, I thought explaining better practices was appropriate. And I honestly thought the title was an intentional joke, I didn't mean to make fun of the patch.

And I agree the idea behind the change is good.

**Comment by Blaisorblade** [comment]
FTR remaining changes have been merged in 5c9c60fefc7ab461dea81f6a094d7b23a718a2bd, so this PR is addressed.

**Pull request closed without merging**
