### PR TITLE
Fix failing build

### PR DESCRIPTION
**Pull request by imapokemon4**

### CODE REVIEW

**Comment by Blaisorblade** [comment]
Can you compare with #145? @jehy Do we need both or is one enough? (Just noticed possible overlap, no clue what's best).

**Comment by farkam135** [comment]
We can just not warn since they aren't used.

**Comment by imapokemon4** [comment]
Yup.  
  
This fixed it for my debug build but to generate a signed apk I only had to put -dontwarn okio.** in pro-guardrules.pro.

**Comment by imapokemon4** [comment]
Actually I'm not even sure I needed it for the debug build. I first tried to generate the apk right off, saw the error and added the dependency and tried to debug and it worked so I thought I needed it.  
  
But yeah I think the dontwarn is enough.

**Comment by jehy** [comment]
Yup, exactly :)

**Pull request closed without merging**
