### PR TITLE
Adding ScrollView to MainActivity Layout to fix 480p screen issues

### PR DESCRIPTION
**Pull request by oskomonzon**
Added ScrollView to the layout
Slight UI changes
New header (Action bar removed)
Strings fixed to adapt to new changes

New look (Spanish locale, taken from my device):
screenshot_2016-08-23-00-35-47

### CODE REVIEW

**Comment by agrajaghh** [comment]
where is the settings button after removing the action bar?

**Comment by oskomonzon** [comment]
@agrajaghh The image is outdated, thanks for letting me notice it. I'll upload a new one and add the missing assets soon.

**Comment by Blaisorblade** [comment]
Sorry for the misassignment. Since @nahojjjen has been following this I'm assigning him for the final decision.

**Comment by oskomonzon** [comment]
Alright, sorry for the delay. I added the missing assets and here's a new screenshot of the Main Activity:
screenshot_2016-08-25-00-51-11

**Comment by agrajaghh** [comment]
you can delete the asset in `drawable-hdpi-v9`, no?

**Comment by oskomonzon** [comment]
@agrajaghh will do. Give me a second.

**Pull request merged**
