### PR TITLE
Move game logic into separate package

### PR DESCRIPTION
**Pull request by Blaisorblade**
Goal: separate core logic from GUI logic. That's just a step to clarify which is which.

I also hope this helps writing unit tests (though @harkin already contributed a way to mock Android, not sure how well that works).

Thoughts?
(Let's be careful with merging this and conflicts on other PRs).

### CODE REVIEW

**Comment by sarav** [comment]
I think this is too soon to move. We still have a bit of refactoring to finish. I think we should wait for things to settle down a bit before moving files.

**Comment by Blaisorblade** [comment]
Is `git blame --follow` not enough? There are no open overlapping PRs, and in fact Git merges renames quite well. (I've rebased this commit N times over tons of changes with 0 manual intervention over `rebase master`).

The architecture I want is basically modularization: specifically `logic` can't depend on anything in the GUI package (not that I can enforce that), on widgets, etc. Declaring stuff to be a module by listing files seems harder to follow and more fragile.

**Comment by sarav** [comment]
Mmm... Ok. Reasonable answers. No strong opinion.

**Comment by harkin** [comment]
> though @harkin already contributed a way to mock Android 

Currently you can mock individual objects with `Mockito` for tests. I didn't set up RoboElectric which shadows all the Android classes

**Comment by Blaisorblade** [comment]
That is: mocking classes takes some work, so using nothing Android-specific in that package simplifies testing?

I think it's simpler to write tests where you don't need to write your own mockins, when possible, and that should work for this package.

**Pull request merged**
