### PR TITLE
Markdown LICENSE.md

### PR DESCRIPTION
**Pull request by DJCrapsody**
Nitpick: LICENSE instead of License (sorry OCD mode on)
Update with markdown, courtesy of @jnrbsn, so it's prettier (like I said, OCD)

### CODE REVIEW

**Comment by nahojjjen** [comment]
Are you only renaming the file, or did you actually delete something? Github says row additions/deletions in this commit is +596-674 which ends up with 78 missing lines.

**Comment by DJCrapsody** [comment]
I changed the entire file, formatted with markdown instead of using the plain template provided by GitHub. You can see from the rich diff intead of source diff. There are some formatting changes done so some lines were added, some lines were removed, causing 78 missing lines (mostly due to *bad* formatting)

**Comment by Blaisorblade** [comment]
Ah, you took it from https://gist.github.com/jnrbsn/708961... which already explains that we're allowed to reformat the GPL (https://gist.github.com/jnrbsn/708961#gistcomment-881408).

**Comment by DJCrapsody** [comment]
Yes we are allowed to reformat as long no words were changed :)

**Comment by Blaisorblade** [comment]
Looks reasonable to me. @nahojjjen you can merge if you find it OK.

**Pull request merged**
