### PR TITLE
Quickfix candy detection for Spanish

### LINKED ISSUE #188: Candy detection doesn't support Spanish
Hi! 
In 2.1.0 GoIV detect correctly the pokemon name, even if you edit it, for example "Machop 76".
In 2.2.0 GoIV can't do that. It's supose to look at the candy name if doesn't get the name but it's not working, at least for me. 
Could be a game language problem? 
Thanks!

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fix #188. Untested.
@oskomonzon / @MalkavSoft can you try this out? (Gotta fix master meanwhile).

### CODE REVIEW

**Comment by MalkavSoft** [comment]
I would like to, but I don't know how.  I guess I have to fork the project, compile it and those things?

**Comment by Blaisorblade** [comment]
@MalkavSoft Don't worry, I suspected, but @oskomonzon is also Spanish so he can check this too.

**Comment by oskomonzon** [comment]
Sorry for the delay, @Blaisorblade. I'll give it a look and report back.

**Comment by Blaisorblade** [comment]
No hurry, this isn't a full-time job!

**Comment by oskomonzon** [comment]
Yes. Seems to be working fine with @Blaisorblade's hotfix. I should have checked that when I was working on the spanish locale.

Good catch, @MalkavSoft. Thanks for the report.-

**Comment by Blaisorblade** [comment]
Thanks for testing! Merged.

**Pull request merged**
