### PR TITLE
update tess-two to 6.1.1

### PR DESCRIPTION
**Pull request by MarcLandis**

### CODE REVIEW

**Comment by nahojjjen** [comment]
Is there a changelog for whats new with tess-two?

**Comment by MarcLandis** [comment]
https://github.com/rmtheis/tess-two/blob/master/CHANGELOG.md

Basically updates the tesseract engine in 6.1.0

**Comment by nahojjjen** [comment]
Does it give better performance / accuracy? Feels like a very vague change-log  -  "Tesseract code updated, version 3.05.00dev"

**Comment by MarcLandis** [comment]
It updates tesseract with all commits done since 25th Dec 2015 until 7th Nov 2016.

**Pull request merged**
