### PR TITLE
Detach CHANGELOG from README

### PR DESCRIPTION
**Pull request by DJCrapsody**
As previously discussed, Added all changelog since 1.3.0. Need to limit on how many changelogs we are keeping, not feasible to keep all changelogs. Maybe maximum of 5?

### CODE REVIEW

**Comment by Blaisorblade** [comment]
> Need to limit on how many changelogs we are keeping, not feasible to keep all changelogs. Maybe maximum of 5?

I see no reason to delete old changelogs, and I haven't seen people do it. I won't require digging them, but I'd accept any PRs adding them. But the PR as-is looks good!
@jehy what do you think?

**Comment by jehy** [comment]
Let's take ACRA as example:
https://github.com/ACRA
On the main page it only publishes last version and has a link to changelog which resides in wiki:
https://github.com/ACRA/acra/wiki/ChangeLog
I thinks that it's a comprehensive method which helps to keep crap it of the repository.

However, that becomes useful only when there are already many version and large volumes of change logs. For now we can be fine with a separate changelog.md file. Bit it should contain all changelogs. And the main readme.md can have a link to this file.

**Comment by DJCrapsody** [comment]
We can follow ACRA, having the version number on the main page and linking to the changelog for others to view the changelogs.

However, they keep changelogs till the first version of a major version. It's 4.9.0 so they keep changelogs till 4.0.0 instead of 3.0.0 or older.

**Comment by jehy** [comment]
Yeah, hovewer older acra's changes can be found in wiki history. I think that that's a good approach.

**Comment by Blaisorblade** [comment]
Again, I don't see reasons to delete old changelogs—they're just at the end. And they're not what makes the repo big.

Anyway, merging this PR for now; we can discuss removing old entries when there's an actual need, if ever.

**Pull request merged**
