### PR TITLE
error with team valor french translation

### PR DESCRIPTION
**Pull request by toinux**
valoriv15 and valoriv13_14 were swapped

### CODE REVIEW

**Comment by DJCrapsody** [comment]
@Remiscan for your review

**Comment by DJCrapsody** [comment]
@Blaisorblade I will rebase on this merge

**Comment by DJCrapsody** [comment]
This PR do not require to be merged, commit has been cherry-picked to #468. PR can be closed.

**Comment by Blaisorblade** [comment]
#468 isn't ready yet, so merging this.

**Pull request merged**
