### PR TITLE
Implementation of auto appraisal scanning

### PR DESCRIPTION
**Pull request by nahojjjen**
Not ready to merge - opening pr so others can take a look at the code & discuss it easier.

### CODE REVIEW

**Comment by MarcLandis** [comment]
So the setStatRangeWith, setHighestStatsWith and setIVRangeWith needs to be language and team specific. Does anyone know if this information is already gathered somewhere?

**Comment by nahojjjen** [comment]
@sarav said he might take a look at making this touch-based instead of poll-based

@MarcLandis Yea, we have which team the player is in, we can get that from settings. As for what the actual quotes are, we have snippets which are used in the drop-down text currently.  We have the full english quotes from other websites. (ex https://rankedboost.com/pokemon-go/appraisal/ )

**Comment by MarcLandis** [comment]
I compiled a version with german strings and it works quite well. The polling is noticable as it take a few moments until the selection is made in the UI.

**Comment by sarav** [comment]
I'll be on vacation with family and won't have much to do. Hoping to work on this then.

**Comment by nahojjjen** [comment]
#623 is an update of this

**Pull request closed without merging**
