### PR TITLE
Theme rework and minor aesthetics fixes

### PR DESCRIPTION
**Pull request by oskomonzon**
Lots of small changes. Adding a screenshot.

### CODE REVIEW

**Comment by oskomonzon** [comment]
This is how it looks now. Should be consistent across screens.-
screenshot_2016-08-27-12-42-46

**Comment by Blaisorblade** [comment]
Testing checkboxes.

**Comment by oskomonzon** [comment]
Made the remaining changes as discussed. Should I attach a new screenshot? (Kinda lazy ATM)

**Comment by Blaisorblade** [comment]
So, application settings are still red which I find a bit unexpected, but otherwise it looks all good! That's IMHO enough to merge it. Thanks!

**Pull request merged**
