### PR TITLE
Added Crashlytics 

### PR DESCRIPTION
**Pull request by rhari991**

### CODE REVIEW

**Comment by chuparCh0pper** [comment]
Can other developers also access Crashlytics?

**Comment by nahojjjen** [comment]
I dont know anything about crashlytics, but is this supposed to be here?

+#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
 +#Wed Aug 17 11:50:17 IST 2016
 +apiSecret=e60292eebe41d0f387a51a976dcfd3152f9ef4df35b56b033867a7577b0bc66c

**Comment by rhari991** [comment]
@nahojjjen My bad, I invalidated that key and added a placeholder
@chuparCh0pper New developers can be added to the Crashlytics project

**Comment by farkam135** [comment]
Once merge conflicts are resolved will be added!

**Comment by farkam135** [comment]
Can you reupdate and fix conflicts again, noticed it's reverting the removal of the scanning toast. Just want to make sure nothing gets reverted, thanks!

**Comment by rhari991** [comment]
My bad, missed a few things. Should be working now.

**Pull request merged**
