### PR TITLE
Change team picker colors + shorten appraisal (fr)

### PR DESCRIPTION
**Pull request by Remiscan**
I changed the colors of the team picker to match the colors used in the Pokémon Go app, because the Instinct color looked a bit green/weird to me.

I also updated the French localization, following the recent changes made to appraisal in #379. And I moved the Instinct strings below the Valor ones, to match the order of the team picker, because I kept reversing them while editing and testing the translation. It makes the "files changed" tab a bit confusing.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
I'd merge translation changes right away as usual, but for the colors I'd ask you to have a separate PR if possible (unless it goes beyond your Git-fu), I'd prefer to leave review for that to others.

**Comment by Remiscan** [comment]
I guess I should really learn how to work with git. And I shouldn't group two unrelated changes in the same pull request.

I don't know how to do that, except I think by creating a new commit that would reverse the color changes, and then create a new pull request with yet another commit to add the color changes again. That would be a bit messy, right?

**Comment by Blaisorblade** [comment]
Yeah that'd be messy. Let's review things as-is.

**Comment by Eremiell** [comment]
You'd probably drop the pr, checkout two new branches and either cherry pick the commits into them or just build them anew using a combination of git stuff and os stuff (copying, some text editor, ...), whichever looks easier for you, but hopefully no one will be against and it could be merged as is (this time).

**Comment by Blaisorblade** [comment]
Given nobody objected to the colors, merging.

**Pull request merged**
